/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author donyc
 */
public class vistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form vistaMenu
     */
    public vistaMenu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/vistas/imagenes/image.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        pnlPrincipalMenu = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnReservacionRest = new javax.swing.JButton();
        btnReservacionHotel = new javax.swing.JButton();
        manubarra = new javax.swing.JMenuBar();
        mnuAcercaDe = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cabeyes Reservation System");

        pnlPrincipalMenu.setBackground(new java.awt.Color(51, 204, 255));
        pnlPrincipalMenu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Seleccione el tipo de reservación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 18), new java.awt.Color(51, 0, 204))); // NOI18N
        pnlPrincipalMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(51, 153, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReservacionRest.setBackground(new java.awt.Color(204, 204, 204));
        btnReservacionRest.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        btnReservacionRest.setForeground(new java.awt.Color(51, 0, 204));
        btnReservacionRest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/restauranticon.png"))); // NOI18N
        btnReservacionRest.setText("Restaurantes        ");
        btnReservacionRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservacionRestActionPerformed(evt);
            }
        });
        pnlMenu.add(btnReservacionRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, 70));

        btnReservacionHotel.setBackground(new java.awt.Color(204, 204, 204));
        btnReservacionHotel.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        btnReservacionHotel.setForeground(new java.awt.Color(51, 0, 204));
        btnReservacionHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/iconohotel.png"))); // NOI18N
        btnReservacionHotel.setText("Hotel / Habitación");
        btnReservacionHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservacionHotelActionPerformed(evt);
            }
        });
        pnlMenu.add(btnReservacionHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 230, 70));

        pnlPrincipalMenu.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, 180));

        mnuAcercaDe.setText("Acerca de");
        mnuAcercaDe.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuAcercaDeMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mnuAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuAcercaDeMouseClicked(evt);
            }
        });
        manubarra.add(mnuAcercaDe);

        setJMenuBar(manubarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAcercaDeMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuAcercaDeMenuKeyPressed

    }//GEN-LAST:event_mnuAcercaDeMenuKeyPressed

    private void mnuAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuAcercaDeMouseClicked

    }//GEN-LAST:event_mnuAcercaDeMouseClicked

    private void btnReservacionRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservacionRestActionPerformed
        vistaReservRte vistaRestaurante = new vistaReservRte();
        vistaRestaurante.setVisible(true);
    }//GEN-LAST:event_btnReservacionRestActionPerformed

    private void btnReservacionHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservacionHotelActionPerformed
        vistaReservHotel vistaHotel = new vistaReservHotel();
        vistaHotel.setVisible(true);
    }//GEN-LAST:event_btnReservacionHotelActionPerformed

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservacionHotel;
    private javax.swing.JButton btnReservacionRest;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar manubarra;
    private javax.swing.JMenu mnuAcercaDe;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipalMenu;
    // End of variables declaration//GEN-END:variables
}
