/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author donyc
 */
public class vistaReservRte extends javax.swing.JFrame {

    /**
     * Creates new form vistaReservRte
     */
    public vistaReservRte() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/vistas/imagenes/image.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalReservRte = new javax.swing.JPanel();
        pnlDatosReservRte = new javax.swing.JPanel();
        btnActualizarRte = new javax.swing.JButton();
        btnCancelarRte = new javax.swing.JButton();
        txtcantidadPersonas = new javax.swing.JTextField();
        txtnumeroReservacionRte = new javax.swing.JTextField();
        btnAgendarRte = new javax.swing.JButton();
        txtcodigoRestaurante = new javax.swing.JTextField();
        txtFechadeReservacion = new javax.swing.JTextField();
        pnlTablaReservRte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservRte = new javax.swing.JTable();
        txtBuscarRte = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cabeyes Reservation System");

        pnlPrincipalReservRte.setBackground(new java.awt.Color(51, 204, 255));
        pnlPrincipalReservRte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Reservaciones de Restaurantes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 18), new java.awt.Color(51, 0, 204))); // NOI18N
        pnlPrincipalReservRte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDatosReservRte.setBackground(new java.awt.Color(51, 153, 255));
        pnlDatosReservRte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Datos de la Reservación", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 14), new java.awt.Color(51, 0, 204))); // NOI18N
        pnlDatosReservRte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizarRte.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        btnActualizarRte.setForeground(new java.awt.Color(51, 0, 204));
        btnActualizarRte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/actualizarIcon.png"))); // NOI18N
        btnActualizarRte.setText("Actualizar Datos");
        pnlDatosReservRte.add(btnActualizarRte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 170, 50));

        btnCancelarRte.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        btnCancelarRte.setForeground(new java.awt.Color(51, 0, 204));
        btnCancelarRte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/cancelarIcon.png"))); // NOI18N
        btnCancelarRte.setText("Cancelar");
        pnlDatosReservRte.add(btnCancelarRte, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 140, 50));

        txtcantidadPersonas.setEditable(false);
        txtcantidadPersonas.setBackground(new java.awt.Color(51, 153, 255));
        txtcantidadPersonas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcantidadPersonas.setForeground(new java.awt.Color(255, 255, 255));
        txtcantidadPersonas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Cantidad de Personas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlDatosReservRte.add(txtcantidadPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 210, 50));

        txtnumeroReservacionRte.setBackground(new java.awt.Color(51, 153, 255));
        txtnumeroReservacionRte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtnumeroReservacionRte.setForeground(new java.awt.Color(255, 255, 255));
        txtnumeroReservacionRte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Número de reservación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtnumeroReservacionRte.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        pnlDatosReservRte.add(txtnumeroReservacionRte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 210, 50));

        btnAgendarRte.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        btnAgendarRte.setForeground(new java.awt.Color(51, 0, 204));
        btnAgendarRte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/agregarIcon.png"))); // NOI18N
        btnAgendarRte.setText("Agendar");
        pnlDatosReservRte.add(btnAgendarRte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 140, 50));

        txtcodigoRestaurante.setBackground(new java.awt.Color(51, 153, 255));
        txtcodigoRestaurante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtcodigoRestaurante.setForeground(new java.awt.Color(255, 255, 255));
        txtcodigoRestaurante.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Codigo de Restaurante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlDatosReservRte.add(txtcodigoRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 210, 50));

        txtFechadeReservacion.setBackground(new java.awt.Color(51, 153, 255));
        txtFechadeReservacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtFechadeReservacion.setForeground(new java.awt.Color(255, 255, 255));
        txtFechadeReservacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Fecha de reservacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlDatosReservRte.add(txtFechadeReservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, 50));

        pnlPrincipalReservRte.add(pnlDatosReservRte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 490, 570));

        pnlTablaReservRte.setBackground(new java.awt.Color(204, 255, 204));
        pnlTablaReservRte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Lista de Reservaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 14), new java.awt.Color(51, 0, 204))); // NOI18N
        pnlTablaReservRte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblReservRte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblReservRte);

        pnlTablaReservRte.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 410));

        txtBuscarRte.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtBuscarRte.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtBuscarRte.setDisabledTextColor(new java.awt.Color(51, 153, 255));
        pnlTablaReservRte.add(txtBuscarRte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 210, 50));

        pnlPrincipalReservRte.add(pnlTablaReservRte, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 640, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalReservRte, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalReservRte, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarRte;
    private javax.swing.JButton btnAgendarRte;
    private javax.swing.JButton btnCancelarRte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDatosReservRte;
    private javax.swing.JPanel pnlPrincipalReservRte;
    private javax.swing.JPanel pnlTablaReservRte;
    private javax.swing.JTable tblReservRte;
    private javax.swing.JTextField txtBuscarRte;
    private javax.swing.JTextField txtFechadeReservacion;
    private javax.swing.JTextField txtcantidadPersonas;
    private javax.swing.JTextField txtcodigoRestaurante;
    private javax.swing.JTextField txtnumeroReservacionRte;
    // End of variables declaration//GEN-END:variables
}
