/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author donyc
 */
public class vistaLogin extends javax.swing.JFrame {

    /**
     * Creates new form vistaLogin
     */
    public vistaLogin() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/vistas/imagenes/image.png")).getImage());
        lbClaveIncorrecta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalLogin = new javax.swing.JPanel();
        pnlLoginDiseno = new javax.swing.JPanel();
        lbImagenlogin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        pswClave = new javax.swing.JPasswordField();
        lbClaveIncorrecta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cabeyes Reservation System");

        pnlPrincipalLogin.setBackground(new java.awt.Color(51, 204, 255));
        pnlPrincipalLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Cabeyes RSystem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Cooper Black", 0, 18), new java.awt.Color(51, 0, 204))); // NOI18N
        pnlPrincipalLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoginDiseno.setBackground(new java.awt.Color(51, 153, 255));
        pnlLoginDiseno.setBorder(new javax.swing.border.MatteBorder(null));
        pnlLoginDiseno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbImagenlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/loginimag.png"))); // NOI18N
        pnlLoginDiseno.add(lbImagenlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 150, 110));

        btnLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnLogin.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLoginDiseno.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 230, -1));

        txtUsuario.setBackground(new java.awt.Color(51, 153, 255));
        txtUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 14), new java.awt.Color(51, 0, 204))); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        pnlLoginDiseno.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 290, 40));

        pswClave.setBackground(new java.awt.Color(51, 153, 255));
        pswClave.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pswClave.setForeground(new java.awt.Color(204, 204, 204));
        pswClave.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Clave", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cooper Black", 0, 14), new java.awt.Color(51, 0, 204))); // NOI18N
        pswClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswClaveKeyPressed(evt);
            }
        });
        pnlLoginDiseno.add(pswClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 290, 40));

        lbClaveIncorrecta.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        lbClaveIncorrecta.setForeground(new java.awt.Color(255, 0, 0));
        lbClaveIncorrecta.setText("Contraseña Incorrecta!!");
        pnlLoginDiseno.add(lbClaveIncorrecta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 270, -1));

        pnlPrincipalLogin.add(pnlLoginDiseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed

    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void pswClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswClaveKeyPressed

    }//GEN-LAST:event_pswClaveKeyPressed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnLogin;
    private javax.swing.JLabel lbClaveIncorrecta;
    private javax.swing.JLabel lbImagenlogin;
    private javax.swing.JPanel pnlLoginDiseno;
    private javax.swing.JPanel pnlPrincipalLogin;
    public javax.swing.JPasswordField pswClave;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
